version: '3.7'
services:
  ingress:
    image: nginx:latest
    container_name: ingress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80

  instance-01:
    image: node:18-alpine
    container_name: instance-01
    working_dir: /usr/app/node
    volumes:
      - .:/usr/app/node
    environment:
      - PORT=5001
      - INSTANCE_NAME=instance-01
    ports:
      - 5001:5001
    command: npm run dev

  instance-02:
    image: node:18-alpine
    container_name: instance-02
    working_dir: /usr/app/node
    volumes:
      - .:/usr/app/node
    environment:
      - PORT=5002
      - INSTANCE_NAME=instance-02
    ports:
      - 5002:5002
    command: npm run dev

  instance-03:
    image: node:18-alpine
    container_name: instance-03
    working_dir: /usr/app/node
    volumes:
      - .:/usr/app/node
    environment:
      - PORT=5003
      - INSTANCE_NAME=instance-03
    ports:
      - 5003:5003
    command: npm run dev